export const countryNamesBR = {
  'QA': 'Catar',
  'EC': 'Equador',
  'GB': 'Inglaterra',
  'IR': 'Iran',
  'SN': 'Senegal',
  'NL': 'Holanda',
  'US': 'EUA',
  'GB-WLS': 'Gales',
  'AR': 'Argentina',
  'SA':'Arabia Saudita',
  'DK': 'Dinamarca',
  'TN': 'Tunísia',
  'MX': 'México',
  'PL' : 'Polônia',
  'FR' : 'França',
  'AU' : 'Austrália',
  'MA' : 'Marrocos',
  'HR': 'Croácia',
  'DE': 'Alemanha',
  'JP' : 'Japão',
  'ES' : 'Espanha',
  'CR' : 'Costa Rica',
  'BE': 'Bélgica',
  'CA' : 'Canadá',
  'CH' : 'Suiça',
  'CM' : 'Camarões',
  'UY' : 'Uruguai',
  'KR' : 'Coreia do Sul',
  'PT' : 'Portugual',
  'GH' : 'Gana',
  'BR' : 'Brasil',
  'RS' : 'Sérvia'
}